#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET 
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17

#undef I2C_DRIVER
#undef I2C1_SDA_PIN
#undef I2C1_SCL_PIN
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP2
#define I2C1_SCL_PIN GP3

#define OLED_BRIGHTNESS 16
#define OLED_TIMEOUT 300000
#define OLED_UPDATE_INTERVAL 100

#undef SPI_DRIVER
#undef SPI_SCK_PIN
#undef SPI_MISO_PIN
#undef SPI_MOSI_PIN
#define SPI_DRIVER SPID1
#define SPI_SCK_PIN GP14
#define SPI_MISO_PIN GP12
#define SPI_MOSI_PIN GP15
#define PMW33XX_CS_PIN GP13

#define POINTING_DEVICE_TASK_THROTTLE_MS 10
#define PMW33XX_CPI 500 // default 2000
#define PMW33XX_LIFTOFF_DISTANCE 0x02 // default 0x02
//#define ROTATIONAL_TRANSFORM_ANGLE 30 // default 0
#define POINTING_DEVICE_INVERT_X